language: python

python:
  - "3.6"
services:
  - "mysql"
env:
  -DJANGO=2.2.6 DB=mysql
install:
  - pip3 install -r requirements.txt
before_script:
  - mysql -e 'create database test;' -u root
script:
  - python3 manage.py test