# Generated by Django 2.2.5 on 2019-09-29 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=255)),
                ('body_type', models.CharField(max_length=255)),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Automaker',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=255)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Car')),
            ],
        ),
    ]
